title:              Spaniel
email:              ellwoose2@gmail.com
description:        Let's not give up!
author:             Spaniel
baseurl:            ""
url:                "https://ellsaria.github.io"

# Social Profiles
twitter_username:   none
github_username:    ellsaria
facebook_username:  spanielellsaria
instagram_username:  none
linkedin_username:  none

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
